// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrOZ4yIZGwydm3RQNwKZ3JvRCsKfr86QU',
    appId: '1:119266369853:web:323e37fe8c4e641de46554',
    messagingSenderId: '119266369853',
    projectId: 'chat-app-7dc0c',
    authDomain: 'chat-app-7dc0c.firebaseapp.com',
    storageBucket: 'chat-app-7dc0c.firebasestorage.app',
    measurementId: 'G-DLFNB8S57Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVp34wwuXXw2w_OreAOg4qDesQnxxicQE',
    appId: '1:119266369853:android:8978d10a8ead6d31e46554',
    messagingSenderId: '119266369853',
    projectId: 'chat-app-7dc0c',
    storageBucket: 'chat-app-7dc0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMz4CNCr7KC_N64usGI72Hm5DnpfSXro',
    appId: '1:119266369853:ios:f4ea5c7e28e0adcbe46554',
    messagingSenderId: '119266369853',
    projectId: 'chat-app-7dc0c',
    storageBucket: 'chat-app-7dc0c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMz4CNCr7KC_N64usGI72Hm5DnpfSXro',
    appId: '1:119266369853:ios:f4ea5c7e28e0adcbe46554',
    messagingSenderId: '119266369853',
    projectId: 'chat-app-7dc0c',
    storageBucket: 'chat-app-7dc0c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFundamentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrOZ4yIZGwydm3RQNwKZ3JvRCsKfr86QU',
    appId: '1:119266369853:web:66755d3ca66b14cfe46554',
    messagingSenderId: '119266369853',
    projectId: 'chat-app-7dc0c',
    authDomain: 'chat-app-7dc0c.firebaseapp.com',
    storageBucket: 'chat-app-7dc0c.firebasestorage.app',
    measurementId: 'G-H1BM9HTEEX',
  );
}
